package com.lOnlyGames.backend;

import com.lOnlyGames.backend.model.Blocked;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;


@RestController
@RequestMapping(path="/block") // This means URL's start with /user (after Application path)

public class BlockUserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BlockedDAO blockedDAO;

    @GetMapping("/allBlockedUsers")
    public @ResponseBody List<Blocked> allBlockedByUser(@RequestParam String blkr_username) {
        return blockedDAO.allBlockedByUser(blkr_username);
    }

    @PostMapping("/blockUser")
    public @ResponseBody String blockUser(@RequestParam String blkr_username, @RequestParam String blkee_username){
        return blockedDAO.blockUser(blkr_username, blkee_username);
    }
}
