package com.lOnlyGames.backend;

import com.lOnlyGames.backend.model.Blocked;
import com.lOnlyGames.backend.model.User;
import com.lOnlyGames.backend.repository.BlockedRepository;
import com.lOnlyGames.backend.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


@RestController
@RequestMapping(path="/user") // This means URL's start with /user (after Application path)

public class BlockUserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BlockedRepository blockRepository;

    @GetMapping("/allBlockedUsers")
    public @ResponseBody Iterable<Blocked> allBlockedUsers() {
        return blockRepository.findAll();
    }

    @PostMapping("/blockUser")
    public @ResponseBody String blockUser(@RequestParam String blkr_username, @RequestParam String blkee_username){
        //User who is doing the blocking
        User blocker = userRepository.findById(blkr_username).get();
        //User who has been blocked
        User blockee = userRepository.findById(blkee_username).get();
        Blocked block = new Blocked(blocker, blockee);

        //saves the blocked item to the db
        blockRepository.save(block);

        //notifies the user that they have blocked the other user
        return blockee + "has been blocked";
    }
}
